# Generated by Django 4.2 on 2023-07-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=255)),
                ("ch_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("views", models.IntegerField()),
                ("dt", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="YoutubeHistory",
        ),
    ]
