# Generated by Django 4.2 on 2023-07-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_youtubedata_delete_youtubehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCountByCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("doc_count", models.IntegerField()),
            ],
        ),
    ]
