# Generated by Django 4.2 on 2023-07-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_documentcountbycategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCountByChannelAndCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("document_count", models.IntegerField()),
                ("channel", models.CharField(max_length=255)),
                ("categories", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentViewsSumByChannelAndCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("document_count", models.IntegerField()),
                ("channel", models.CharField(max_length=255)),
                ("categories", models.CharField(max_length=255)),
                ("views_sum", models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="documentcountbycategory",
            old_name="key",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="documentcountbycategory",
            old_name="doc_count",
            new_name="document_count",
        ),
    ]
