# Generated by Django 4.2 on 2023-07-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_remove_documentviewssumbychannelandcategory_categories"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentCountByChannelAndCategory",
        ),
    ]
